### PR TITLE
Update problem.h

### PR DESCRIPTION
**Pull request by Unril**
Removed unnecessary memory allocation and number conversions warnings.

### CODE REVIEW

**Comment by spinicist** [comment]
Hello. Thank you for the input. Before I merge this:
1 - Please don't close a PR and open a new one when you make small changes. Either just add another commit, or even better do a `git push --force` to your branch. Travis will pick up the latter and try a fresh set of checks.
2 - Run the linter, `make lint` and check it passes.
3 - I prefer Eigen::Index over ptrdiff_t, as it is possible for someone to change the Index type in Eigen (via the EIGEN_DEFAULT_DENSE_INDEX_TYPE).
4 - Isn't a better way of avoiding the memory allocations to declare the constants as `static const std::vector...` or even `static const std::array`?

**Comment by Unril** [comment]
1, 2 - Ok.
3 - It seems that Eigen::Index typedef isn't present is some Eigen versions. I should be something like typename TVector::Index.
4 - Allocating small array on stack should be better because it improves data locality. Though there are still 2 TVector allocation on heap in that function. So difference is negligible I think.

**Comment by spinicist** [comment]
3 - Ah, yes. I think Eigen::Index has been added for 3.3, it doesn't seem to be present in 3.2.3. I think a Problem::Index typedef might be best. TVector is a typedef for Eigen::Matrix<>.
4 - Now I added the Dimension template parameter to Problem, if that is specified then fixed size Eigen::Vectors will be used, which are allocated on the stack where possible. My main issue with the raw arrays as you have them is the extra 0 bytes, which doesn't seem good style to me?

**Comment by Unril** [comment]
As I've measured there is no difference between array, static array and static vector. Not static vector ~20 times slower. 

Also it is possible not to use memory allocation even with VectorXd. Performance almost the same as in fixed sixe vector case:
```c++
  void finiteGradient(const  TVector &x, TVector &grad, int accuracy = 0) {
    // accuracy can be 0, 1, 2, 3
    const Scalar eps = 2.2204e-6;
    static const std::vector<std::vector<Scalar>> coeff =
    { {1, -1}, {1, -8, 8, -1}, {-1, 9, -45, 45, -9, 1}, {3, -32, 168, -672, 672, -168, 32, -3} };
    static const std::vector<std::vector<Scalar>> coeff2 =
    { {1, -1}, {-2, -1, 1, 2}, {-3, -2, -1, 1, 2, 3}, {-4, -3, -2, -1, 1, 2, 3, 4} };
    const Scalar dd[4] = {2, 12, 60, 840};

    grad.resize(x.rows());
    TVector& xx = const_cast<TVector&>(x);
    const int innerSteps = 2*(accuracy+1);

    const Scalar *coeffPtr = coeff[accuracy].data();
    const Scalar *coeff2Ptr = coeff2[accuracy].data();
    const Scalar ddVal = dd[accuracy]*eps;
    for (TIndex d = 0; d < x.rows(); d++) {
      grad[d] = 0;
      for (int s = 0; s < innerSteps; ++s)
      {
        Scalar tmp = xx[d];
        xx[d] += coeff2Ptr[s]*eps;
        grad[d] += coeffPtr[s]*value(xx);
        xx[d] = tmp;
      }
      grad[d] /= ddVal;
    }
  }
```

**Comment by PatWie** [comment]
I rebased your changes to the master branch and replace the outer-vector by an std::array. I wasn't aware that there is such a significant difference.

**Pull request closed without merging**
