### PR TITLE
Bounded problem

### LINKED ISSUE #41: Add the dimension as template parameter
I find it often very confusing and inconvenient that the dimension is not a template argument of the problem. Wouldn't it make sense to add it there?

Then you don't always have to find out the dimension dynamically.

### PR DESCRIPTION
**Pull request by spinicist**
This is a Work in Progress aimed at solving #32, #40 and #41. Currently fixes #41.

Benchmark is reporting failures, but these seem to be present in master as well.

### CODE REVIEW

**Comment by spinicist** [comment]
The clang builds are failing because LLVM have taken their packages off-line, so Travis can't install them. See this thread here: https://github.com/travis-ci/apt-source-whitelist/issues/156. I have subscribed to it and once someone posts a good solution I will implement it. gcc is passing.

I had an odd problem with the linter - I had some {} that weren't aligned, but the linter won't print out the file that this occurs in, only the line numbers. @PatWie, where did you get the linter code from?

**Comment by PatWie** [comment]
Just want to write, that I will look into it.

**Comment by PatWie** [comment]
I get

```
patwie@patwie-Desktop~/scratch/tmp/solver/build (master) $ git remote add fork https://github.com/spinicist/CppNumericalSolvers.git
patwie@patwie-Desktop~/scratch/tmp/solver/build (master) $ git fetch fork BoundedProblem
...
patwie@patwie-Desktop~/scratch/tmp/solver/build (BoundedProblem) $ make lint
-- Configuring done
-- Generating done
-- Build files have been written to: /home/patwie/scratch/tmp/solver/build
Scanning dependencies of target lint


-- Linter did not find any errors!
Built target lint
```

Your code seems fine to me.

**Comment by spinicist** [comment]
@PatWie - Sorry for slow response. Part of your message got chopped off in my inbox. I fixed the problems with {}, but I had to temporarily hack the linter to make it print out the file where it was finding problems. It was a very odd bug!

I removed the Clang builds from Travis. I am following the thread about the problem and will put them back when someone posts a good solution.

I went ahead and merged this so we can close the issues and pull requests related to it. I'm happy to change things back if people object.

**Comment by PatWie** [comment]
Really nice work!
Since g++ works, it is fine for me. I will try to fix this weekend the clang issue, if possible. I am curious about your CMAES modifications, too.

**Comment by spinicist** [comment]
Ah, you noticed those! I am about to open another Pull Request, wanted to get this done first.

**Pull request merged**
