### PR TITLE
Added variable NO_GOOGLE_TEST

### PR DESCRIPTION
**Pull request by hugandr**
If this variable is set, the google testing library is not included in problem.h.

This allows to circumvent to usage of gtest. I had some problems with gtest when compiling my program on a different machine even tough I only used the solver and didn't need the gtest functionality.

I guess most people using this library don't really need gtest.

### CODE REVIEW

**Comment by spinicist** [comment]
Hello, I have had similar issues but I don't think expecting the user to declare a #define just to use the library is the right approach.

@patwie - I think it would be better to remove the `EXPECT_NEAR` calls in problem.h. If we want to provide some checks of the numerical gradients that should be done in a test, not in problem.h itself.

**Comment by hugandr** [comment]
@spinicist: I agree, this would be the cleaner approach.

As discussed in issue #32, I implemented a subclass `BoundedProblem` and moved all the methods concerning the bounds into this class. 

The bounds now have to be set via the base constructor inside the class that inherits from the BoundedProblem class. Probably the current implementation is a bit too strict with setting the bounds but this could also be relaxed a bit. 

One could also add helper function to create partially bounded problem, so that one doesn't always have to write `Vector<T>::Ones(DIM)*std::numeric_limits<T>::infinity()`. The reason I haven't implemented this yet is related to the issue #41. Since one doesn't know the dimension during compile time (or in the constructor) this isn't really possible yet.

What do you think about changes?

**Comment by spinicist** [comment]
@hugandr I hit the same issues about dimensions when I was trying to implement a BoundedProblem subclass. However allowing the dimension of the solver to be fixed proved to be quite a substantial refactor and I haven’t had time to finish it. Give me until the weekend and I will try to finish what I’ve started and put up a branch for people to look at.

**Comment by PatWie** [comment]
The idea of removing GTEST stuff from the library is good! But there are some errors found by the linter.

About the dimension: How about adding the dimension of the input as a template parameter. This would even allow for some compiler optimizations?

**Comment by spinicist** [comment]
Closing this because @43 should fix it. @hugandr Let me know if it doesn't.

**Pull request closed without merging**
