### PR TITLE
Stop criteria

### PR DESCRIPTION
**Pull request by spinicist**
Hi,
By looking at some other solvers I finally realised that the Options struct should really be called Criteria. I then added a Status enum and generalised the checkConvergence function in meta.h to use the stopping Criteria and return the Status. Then I made most of the solvers use this function and added utility functions to e.g. print Status codes.

There is then a minor edit as a second commit that allows the user to change the history size (m) for LBFGSB, as this is a property of the solver and not something to do with convergence.

This is based of the gtest branch as that is the only way I can run the tests.

Cheers!

### CODE REVIEW

**Comment by spinicist** [comment]
The Travis builds are failing but I don't think it's an issue with my changes - verify & benchmark compile and run on my system, and I fixed some lint problems.

In Travis, clang seems to fail because the gtest submodule hasn't been initialised. The gcc build seems to be stuck in an infinite loop where it is continually running cmake.

Any ideas?

**Comment by PatWie** [comment]
Nice! Just add

`- git submodule update --init --recursive`

to `before_install`. It should look like:

 ```
# ....
 - g++
before_install:
  - chmod u+x get_dependencies.sh
  - ./get_dependencies.sh
  - git submodule update --init --recursive
script:
  - cp CppNumericalSolvers.config.example CppNumericalSolvers.config
  - mkdir build
  - cd build
  - cmake ..
# ...
```

To get the Gtest stuff work. But it still failes. Did you use my "gtest" branch? There is still an issue with the gtest:

https://travis-ci.org/PatWie/CppNumericalSolvers/jobs/125246665

Not sure yet, how to solve this.

**Comment by spinicist** [comment]
Yes, this is based off the gtest branch.

Unfortunately I don't actually know a great deal about Travis. It looks to me like the include directories aren't being passed to the compiler correctly. Is there any way to get Travis to do a verbose make (make benchmark VERBOSE=1)?

Personally I think the tests should stay with the library. It's the best way to get other people interested in development.

**Comment by PatWie** [comment]
It is not an issue with travis. Doing the same locally I get the same effect.

**Comment by spinicist** [comment]
Okay, I am very confused. It works fine on my system!

I fixed the Travis gcc infinite loop problem by removing the SET(CMAKE_CXX_COMPILER "clang++") line in the .config file. The gcc build now runs, but fails to build Google Mock. I am pretty sure this is because the default Travis gcc is 4.6.3 and so doesn't support some C++11 features (http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/)

I tried adding ${PROJECT_SOURCE_DIR} before gtest_root, which works fine on my system but also fails in Travis. What CMake version & compiler are you running? I have CMake 3.5.0 & Apple LLVM 7.0.2 (unfortunately Apple version numbers don't correspond to upstream LLVM anymore).

**Comment by spinicist** [comment]
Ha! I got the Travis builds to work.

The problems seem to have been the old compilers that are in Travis by default. By taking inspiration from here: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/ and here: http://stackoverflow.com/questions/33196136/travis-ci-update-cmake-using-the-packages-cache I got Travis to use GCC 4.9, 5.0, Clang 3.6, 3.7 and CMake 3.3.

CMake added CMAKE_CXX_STANDARD CMAKE_CXX_STANDARD_REQUIRED settings around version 3.1 which make specifying C++11 far easier.

**Comment by PatWie** [comment]
This is awesome! I had no glue how to include the gtest stuff appropriately.

**Pull request merged**
