### PR TITLE
Iterations

### PR DESCRIPTION
**Pull request by spinicist**
I needed to get the number of iterations performed by the optimiser, so I added a member variable to isolver and made all the solvers use it instead of local variables.

### CODE REVIEW

**Comment by PatWie** [comment]
Everything is fine, but the linter is not happy with whitespaces at the end of a line. 
Thanks for your time!
Could please also rebase to the master-branch and squeeze these commits into one commit?

What about a "info-struct" contain all information like iter, grad.norm, ... ?

**Comment by spinicist** [comment]
Hi, no problem and thanks for writing the solvers in the first place!

Following your suggestion I changed ISolver so it now keeps two Options structs - one is the 'Control' set by the user, and defines maximum iteratons, gradient norm etc. The other is the 'Information', which keeps track of the gradient norm and iterations during minimization and can be queried by the user at the end.

I got a bit carried away with changes - for instance I renamed Options to Info and moved it to be a member class of ISolver, so that the gradient norm and rate variables can be the same precision as the solver. I added a constructor so that solvers can be instantiated with the controls already set, which saves a line of typing.

I'm happy to make further changes or roll some of these back if you don't like them. I was struggling to come up with a good name for the Options/Info struct, as now it is kind of both at the same time.

Questions:
1 - Style. Should tabs be 4 spaces or 2? In /solvers, they are 2 spaces, but in /linesearch, they seem to be 4.
2 - What are the 'rate' and 'm' variables in the Options structure? Can they be given more verbose names?

**Comment by PatWie** [comment]
Awesome stuff! I didn't though about this way controlling the optimization-parameters. This see like a good way of tracking stuff. I like your naming-convention.

1. I worked on different machines with different Sublime-Settings. You are free to choose 2 or 4 spaces. I will adjust the other files to _your_ preference :-) and I will edit the `lint.py` to check future commits

2. "`m`" was intended as a parameter for the inverse hessian-approximation within L-BFGS(-B), "`rate`" is from the very first implementation using a constant stepsize=rate. Now, I see that `m` is hard-coded (ignored) [here ](https://github.com/PatWie/CppNumericalSolvers/blob/c1b9a3ad42a73d304770c5b33891046045865355/include/cppoptlib/solver/lbfgssolver.h#L17) but used [here](https://github.com/PatWie/CppNumericalSolvers/blob/c1b9a3ad42a73d304770c5b33891046045865355/include/cppoptlib/solver/lbfgsbsolver.h#L250).

All I want you to ask is just to add another example for the usage of the control- and info-struct. And a rebase to the master branch to make sure this squeezes into one single commit.

Should be something like
```
git checkout iterations
git rebase -i master
(pick the first, reword the second and fixup the other commits)
git push -f origin iterations
```

**Comment by spinicist** [comment]
Great. I will work on the example and squeezing the commits together - although I've used git for my own projects for a long time, I have not really learnt or the collaboration features.

Re: tabs/spaces - In my experience 4 is more common. If you're happy to go with that I'll change the commits over to 4. This will mean changing quite a few files though?

**Comment by PatWie** [comment]
So have to commits:
- this features
- and another fixing the whitespaces

**Comment by spinicist** [comment]
I've squashed the commits together, I hope this is okay now. Thanks again.

In future it might need expanding so that different solvers have different Info structures, as not all solvers use the same conditions. But I think it's best to deal with that when the situation arises.

I can do another PR for the whitespace, but it might be easier for you to fix yourself?

**Comment by PatWie** [comment]
Seems to be fine. Let me do the boring work of adjusting white-spaces.

**Pull request merged**
